# coding: utf-8

"""
    RIXL API

    **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

    The version of the OpenAPI document: 2.0
    Contact: support@rixl.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rixl_images_sdk.models.pagination_paginated_response_image import PaginationPaginatedResponseImage

class TestPaginationPaginatedResponseImage(unittest.TestCase):
    """PaginationPaginatedResponseImage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginationPaginatedResponseImage:
        """Test PaginationPaginatedResponseImage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginationPaginatedResponseImage`
        """
        model = PaginationPaginatedResponseImage()
        if include_optional:
            return PaginationPaginatedResponseImage(
                data = [
                    rixl_images_sdk.models.image.Image(
                        attached_to_video = False, 
                        file = rixl_images_sdk.models.file.File(
                            created_at = '2025-01-01T00:00:00Z', 
                            format = 'avif', 
                            id = 'FpvLwyDMqu', 
                            name = 'original.jpeg', 
                            project_id = 'Bq4y3QB38S', 
                            size = 1048576, 
                            status = "ready", 
                            updated_at = '2025-01-01T00:00:00Z', 
                            url = 'https://images.rixl.com/Bq4y3QB38S/FpvLwyDMqu', ), 
                        height = 1080, 
                        id = 'PS5IMKoFLm', 
                        thumbhash = '1QcSHQRnh493V4dIh4eXh1h4kJUI', 
                        width = 1920, )
                    ],
                pagination = rixl_images_sdk.models.pagination/pagination.pagination.Pagination(
                    limit = 100, 
                    offset = 50, 
                    total = 1000, )
            )
        else:
            return PaginationPaginatedResponseImage(
        )
        """

    def testPaginationPaginatedResponseImage(self):
        """Test PaginationPaginatedResponseImage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
