# coding: utf-8

"""
    RIXL API

    **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

    The version of the OpenAPI document: 2.0
    Contact: support@rixl.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rixl_images_sdk.api.images_api import ImagesApi


class TestImagesApi(unittest.TestCase):
    """ImagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImagesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_images_image_id(self) -> None:
        """Test case for delete_images_image_id

        Delete image
        """
        pass

    def test_get_images(self) -> None:
        """Test case for get_images

        List images for a project
        """
        pass

    def test_get_images_image_id(self) -> None:
        """Test case for get_images_image_id

        Get image
        """
        pass

    def test_post_images_upload_complete(self) -> None:
        """Test case for post_images_upload_complete

        Upload: Mark as complete
        """
        pass

    def test_post_images_upload_init(self) -> None:
        """Test case for post_images_upload_init

        Upload: Init
        """
        pass


if __name__ == '__main__':
    unittest.main()
