# coding: utf-8

"""
    RIXL API

    **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

    The version of the OpenAPI document: 2.0
    Contact: support@rixl.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rixl_images_sdk.models.internal_images_handler_init_response import InternalImagesHandlerInitResponse

class TestInternalImagesHandlerInitResponse(unittest.TestCase):
    """InternalImagesHandlerInitResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalImagesHandlerInitResponse:
        """Test InternalImagesHandlerInitResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalImagesHandlerInitResponse`
        """
        model = InternalImagesHandlerInitResponse()
        if include_optional:
            return InternalImagesHandlerInitResponse(
                image_id = 'PS5IMKoFLm',
                presigned_url = 'https://images.rixl.com/Bq4y3QB38S/PS5IMKoFLm?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAEXAMPLE%2F20250831%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250831T103000Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=b228dbec8c1008c80c162e1210e4503dceead1e4d4751b4d9787314fd6da4d55',
                upload_expires = 1640995200
            )
        else:
            return InternalImagesHandlerInitResponse(
        )
        """

    def testInternalImagesHandlerInitResponse(self):
        """Test InternalImagesHandlerInitResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
