# coding: utf-8

"""
    RIXL API

    **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

    The version of the OpenAPI document: 2.0
    Contact: support@rixl.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rixl_videos_sdk.api.videos_api import VideosApi


class TestVideosApi(unittest.TestCase):
    """VideosApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VideosApi()

    def tearDown(self) -> None:
        pass

    def test_delete_videos_video_id_audio_tracks(self) -> None:
        """Test case for delete_videos_video_id_audio_tracks

        Delete all audio tracks
        """
        pass

    def test_delete_videos_video_id_audio_tracks_lang_code(self) -> None:
        """Test case for delete_videos_video_id_audio_tracks_lang_code

        Delete audio track by language
        """
        pass

    def test_delete_videos_video_id_audio_tracks_track_id(self) -> None:
        """Test case for delete_videos_video_id_audio_tracks_track_id

        Delete audio track
        """
        pass

    def test_delete_videos_video_id_chapters(self) -> None:
        """Test case for delete_videos_video_id_chapters

        Delete video chapters
        """
        pass

    def test_delete_videos_video_id_delete(self) -> None:
        """Test case for delete_videos_video_id_delete

        Delete video
        """
        pass

    def test_delete_videos_video_id_subtitles(self) -> None:
        """Test case for delete_videos_video_id_subtitles

        Delete all subtitles
        """
        pass

    def test_delete_videos_video_id_subtitles_lang_code(self) -> None:
        """Test case for delete_videos_video_id_subtitles_lang_code

        Delete subtitle by language
        """
        pass

    def test_delete_videos_video_id_subtitles_subtitle_id(self) -> None:
        """Test case for delete_videos_video_id_subtitles_subtitle_id

        Delete subtitle
        """
        pass

    def test_get_videos(self) -> None:
        """Test case for get_videos

        List videos for a project
        """
        pass

    def test_get_videos_languages(self) -> None:
        """Test case for get_videos_languages

        List available subtitle languages
        """
        pass

    def test_get_videos_video_id(self) -> None:
        """Test case for get_videos_video_id

        Get a video
        """
        pass

    def test_post_videos_upload_complete(self) -> None:
        """Test case for post_videos_upload_complete

        Upload: Mark as complete
        """
        pass

    def test_post_videos_upload_init(self) -> None:
        """Test case for post_videos_upload_init

        Upload: Init
        """
        pass

    def test_post_videos_video_id_audio_tracks(self) -> None:
        """Test case for post_videos_video_id_audio_tracks

        Bulk upsert video audio tracks
        """
        pass

    def test_post_videos_video_id_subtitles(self) -> None:
        """Test case for post_videos_video_id_subtitles

        Bulk upsert video subtitles
        """
        pass

    def test_put_videos_video_id_audio_tracks_lang_code(self) -> None:
        """Test case for put_videos_video_id_audio_tracks_lang_code

        Upsert video audio track
        """
        pass

    def test_put_videos_video_id_chapters(self) -> None:
        """Test case for put_videos_video_id_chapters

        Update video chapters
        """
        pass

    def test_put_videos_video_id_subtitles_lang_code(self) -> None:
        """Test case for put_videos_video_id_subtitles_lang_code

        Upsert video subtitle
        """
        pass

    def test_put_videos_video_id_thumbnail(self) -> None:
        """Test case for put_videos_video_id_thumbnail

        Update video thumbnail
        """
        pass


if __name__ == '__main__':
    unittest.main()
