# coding: utf-8

"""
    RIXL API

    **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

    The version of the OpenAPI document: 2.0
    Contact: support@rixl.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rixl_videos_sdk.models.audio_track import AudioTrack

class TestAudioTrack(unittest.TestCase):
    """AudioTrack unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AudioTrack:
        """Test AudioTrack
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AudioTrack`
        """
        model = AudioTrack()
        if include_optional:
            return AudioTrack(
                created_at = '2025-12-21T12:00:00Z',
                format = 'mp3',
                id = '3n7v9k4m2p',
                label = 'Spanish',
                language_code = 'es-ES',
                name = 'spanish_audio.mp3',
                size = 2048576,
                url = 'https://cdn.rixl.io/audio_tracks/project_id/video_id/es-ES-3n7v9k4m2p.mp3',
                video_id = 'x8n2p5v9k7'
            )
        else:
            return AudioTrack(
        )
        """

    def testAudioTrack(self):
        """Test AudioTrack"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
