# coding: utf-8

"""
    RIXL API

    **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

    The version of the OpenAPI document: 2.0
    Contact: support@rixl.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rixl_videos_sdk.models.github_com_qeeqez_api_db_sqlc_video_quality import GithubComQeeqezApiDbSqlcVideoQuality

class TestGithubComQeeqezApiDbSqlcVideoQuality(unittest.TestCase):
    """GithubComQeeqezApiDbSqlcVideoQuality unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGithubComQeeqezApiDbSqlcVideoQuality(self):
        """Test GithubComQeeqezApiDbSqlcVideoQuality"""
        # inst = GithubComQeeqezApiDbSqlcVideoQuality()

if __name__ == '__main__':
    unittest.main()
