# coding: utf-8

"""
    RIXL API

    **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

    The version of the OpenAPI document: 2.0
    Contact: support@rixl.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rixl_videos_sdk.models.github_com_qeeqez_api_internal_videos_handler_upload_init_response import GithubComQeeqezApiInternalVideosHandlerUploadInitResponse

class TestGithubComQeeqezApiInternalVideosHandlerUploadInitResponse(unittest.TestCase):
    """GithubComQeeqezApiInternalVideosHandlerUploadInitResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GithubComQeeqezApiInternalVideosHandlerUploadInitResponse:
        """Test GithubComQeeqezApiInternalVideosHandlerUploadInitResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GithubComQeeqezApiInternalVideosHandlerUploadInitResponse`
        """
        model = GithubComQeeqezApiInternalVideosHandlerUploadInitResponse()
        if include_optional:
            return GithubComQeeqezApiInternalVideosHandlerUploadInitResponse(
                poster_id = 'PS5IMKoFLm',
                poster_presigned_url = 'https://images.rixl.com/Bq4y3QB38S/PS5IMKoFLm?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAEXAMPLE%2F20250831%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250831T103000Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=b228dbec8c1008c80c162e1210e4503dceead1e4d4d55',
                upload_expires = 1640995200,
                video_id = 'VI9VXQxWXQ',
                video_presigned_url = 'https://videos.rixl.com/Bq4y3QB38S/VI9VXQxWXQ?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAEXAMPLE%2F20250831%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250831T103000Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=b228dbec8c1008c80c162e1210e4503dceead1e4d4d55'
            )
        else:
            return GithubComQeeqezApiInternalVideosHandlerUploadInitResponse(
        )
        """

    def testGithubComQeeqezApiInternalVideosHandlerUploadInitResponse(self):
        """Test GithubComQeeqezApiInternalVideosHandlerUploadInitResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
