# coding: utf-8

"""
    RIXL API

    **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

    The version of the OpenAPI document: 2.0
    Contact: support@rixl.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rixl_videos_sdk.models.subtitle_delete import SubtitleDelete

class TestSubtitleDelete(unittest.TestCase):
    """SubtitleDelete unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubtitleDelete:
        """Test SubtitleDelete
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubtitleDelete`
        """
        model = SubtitleDelete()
        if include_optional:
            return SubtitleDelete(
                message = 'Subtitle deleted',
                status = 'ok'
            )
        else:
            return SubtitleDelete(
        )
        """

    def testSubtitleDelete(self):
        """Test SubtitleDelete"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
