# coding: utf-8

"""
    RIXL API

    **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

    The version of the OpenAPI document: 2.0
    Contact: support@rixl.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, Dict, List, Optional
from rixl_videos_sdk.models.github_com_qeeqez_api_internal_videos_handler_upload_complete_request import GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

POSTVIDEOSUPLOADCOMPLETEREQUEST_ONE_OF_SCHEMAS = ["GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest", "object"]

class PostVideosUploadCompleteRequest(BaseModel):
    """
    PostVideosUploadCompleteRequest
    """
    # data type: object
    oneof_schema_1_validator: Optional[Dict[str, Any]] = None
    # data type: GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest
    oneof_schema_2_validator: Optional[GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest] = Field(default=None, description="Video upload completion request")
    actual_instance: Optional[Union[GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest, object]] = None
    one_of_schemas: Set[str] = { "GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest", "object" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = PostVideosUploadCompleteRequest.model_construct()
        error_messages = []
        match = 0
        # validate data type: object
        try:
            instance.oneof_schema_1_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest
        if not isinstance(v, GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in PostVideosUploadCompleteRequest with oneOf schemas: GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest, object. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in PostVideosUploadCompleteRequest with oneOf schemas: GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest, object. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into object
        try:
            # validation
            instance.oneof_schema_1_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_1_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest
        try:
            instance.actual_instance = GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into PostVideosUploadCompleteRequest with oneOf schemas: GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest, object. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into PostVideosUploadCompleteRequest with oneOf schemas: GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest, object. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest, object]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


